version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # Root workspace
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # App
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/core
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/env
  - package-ecosystem: "npm"
    directory: "/packages/env"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/logger
  - package-ecosystem: "npm"
    directory: "/packages/logger"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/shared
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/shared-ui
  - package-ecosystem: "npm"
    directory: "/packages/shared-ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # packages/youtube
  - package-ecosystem: "npm"
    directory: "/packages/youtube"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
