version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    groups:
      dependencies:
        dependency-type: production
      devDependencies:
        dependency-type: development