name = "playlist-actions-job-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[queues.consumers]]
queue = "playlist-actions-job-queue"
max_concurrency = 5
max_retries = 3
retry_delay = 30

[[queues.producers]]
queue = "playlist-actions-job-queue"
binding = "PLAYLIST_QUEUE"

[triggers]
crons = ["*/30 * * * *"]

[env.staging]
name = "playlist-actions-job-worker-staging"

[[env.staging.queues.consumers]]
queue = "playlist-actions-job-queue-staging"
max_concurrency = 5
max_retries = 3
retry_delay = 30

[[env.staging.queues.producers]]
queue = "playlist-actions-job-queue-staging"
binding = "PLAYLIST_QUEUE"

[env.staging.triggers]
crons = ["*/30 * * * *"]

