name: Lint & format

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  oxc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm and Install dependencies
        uses: ./.github/workflows/scripts/pnpmInstall
        with:
          devDeps: true
      - name: Run Oxlint
        run: pnpm lint
      - name: Run Oxfmt
        run: pnpm format:check
